apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-quota
  namespace: my-namespace
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: "16Gi"
    limits.cpu: "8"
    limits.memory: "32Gi"
# pods: Limita el número total de Pods a 10.
# requests.cpu: Limita el total de CPU solicitada a 4 CPU.
# requests.memory: Limita el total de memoria solicitada a 16 GiB.
# limits.cpu: Limita el total de CPU máxima a 8 CPU.
# limits.memory: Limita el total de memoria máxima a 32 GiB.