apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: myapp
        image: nginx:1.20
        resources:
          limits:
            memory: "256Mi"
            cpu: "128m"
        # ports:
        # - containerPort: <Port>