# A node with taint
# kubectl taint nodes node01 spray=mortein:NoSchedule
# Create a pod named bee with the nginx image, which has a toleration set to the taint mortein
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: bee
  name: bee
spec:
  containers:
  - image: nginx
    name: bee
  tolerations:
  - key: spray
    value: mortein
    effect: NoSchedule
    operator: Equal